### ISSUE TITLE
Register research object in Rohub

### ISSUE THREAD

**Issue by backeb** [c-scale-community/workflow-coastal-hydrowaq#50]
https://reliance.rohub.org/

**Comment by sebastian-luna-valero** [comment]
Can this be considered done?

https://w3id.org/ro-id/56c970ea-ef0c-4963-845e-1155bad0682a

**Comment by backeb** [comment]
Yes.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
